SELECT LPAD(' ',(LEVEL-1)*2,' ')||ENAME AS 이름 ,EMPNO, MGR, LEVEL
FROM EMP
START WITH ENAME ='KING'
CONNECT BY PRIOR EMPNO=MGR;

SELECT ENAME, SAL
FROM EMP
ORDER BY SAL desc;

SELECT JOB, AVG(SAL)AS '평균' FROM EMP GROUP BY JOB;
